POST http://localhost:3000/api/auth/login HTTP/1.1
content-type: application/json

{
  "email": "job_seeker@local.com",
  "password": "321Assdx"
}


###

GET http://localhost:3000/api/users
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImZ1bGxOYW1lIjoiYWRtaW4iLCJyb2xlIjoicmVjcnVpdGVyIiwiaWF0IjoxNjc5OTMzNzg3LCJleHAiOjE2ODAwMjAxODd9.Qtrff2KLHoWTSVP_ObZrlN2azTTtHUUVzwTSwltT6LE

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "fullName": "job_seeker",
  "email": "job_seeker@local.com",
  "password": "321Assdx",
  "genre": "Male",
  "age": 25,
  "phoneNumber": "+1234567890",
  "role": "job_seeker",
  "skills": ["LOL"],
  "degrees": ["LOL"],
  "majors": ["LOL"]
}


###

DELETE http://localhost:3000/api/users/12 HTTP/1.1

###

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
  "fullName": "recruiter",
  "email": "recruiter@local.com",
  "password": "321Assdx",
  "genre": "Male",
  "age": 25,
  "phoneNumber": "+1234567890",
  "role": "recruiter",
  "company": "e-Recruiter"
}

###

PUT http://localhost:3000/api/users/2 HTTP/1.1
content-type: application/json

{
  "fullName": "adminae",
  "email": "admins@local.com",
  "password": "321Assdx",
  "age": 25,
  "phoneNumber": 321467890,
  "role": "recruiter",
  "company": "TheDreams"
}
